server:
  port: 8000
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useSSL=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: Aspire09
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
springdoc:
  api-docs:
    path: cambio-service/v3/api-docs
